# Generated by Django 3.0.2 on 2020-02-29 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnGoingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('unit_size', models.CharField(max_length=100)),
                ('expected_completion', models.DateField()),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
