# Generated by Django 3.0.2 on 2020-02-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongoingproject',
            name='ogp_img',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
