# Generated by Django 3.0.2 on 2020-02-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_home', '0002_ongoingproject_ogp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongoingproject',
            name='ogp_img',
            field=models.ImageField(blank=True, default='default.png', upload_to='ongoing_project_img'),
        ),
    ]
