# Generated by Django 3.0.2 on 2020-03-01 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spl_home', '0003_auto_20200229_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('unit_size', models.CharField(max_length=100)),
                ('ucp_img', models.ImageField(blank=True, default='default.png', upload_to='ongoing_project_img')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
