# Generated by Django 3.0.2 on 2020-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_home', '0004_upcomingproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingproject',
            name='ucp_img',
            field=models.ImageField(blank=True, default='default.png', upload_to='upcoming_project_img'),
        ),
    ]
