# Generated by Django 3.0.2 on 2020-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_home', '0007_auto_20200301_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_count', models.CharField(max_length=100)),
                ('home_img', models.ImageField(blank=True, default='default.png', upload_to='home_img')),
            ],
        ),
    ]
