# Generated by Django 3.0.2 on 2020-03-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spl_home', '0008_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='img_count',
        ),
    ]
