# Generated by Django 3.0.2 on 2020-03-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_home', '0009_remove_home_img_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img_count',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
